CREATE TABLE funcionario
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    empresa_id       BIGINT,
    funcao_id        BIGINT,
    nome             VARCHAR(255),
    sobrenome        VARCHAR(255),
    status           VARCHAR(255),
    email            VARCHAR(255),
    data_contratacao date,
    CONSTRAINT pk_funcionario PRIMARY KEY (id)
);

CREATE TABLE produto
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo_ean        VARCHAR(255),
    empresa_id        INTEGER,
    ingrediente_id    INTEGER,
    unidade_medida_id INTEGER,
    nome              VARCHAR(255),
    quantidade        INTEGER,
    descricao         VARCHAR(255),
    marca             VARCHAR(255),
    validade          date,
    CONSTRAINT pk_produto PRIMARY KEY (id)
);

CREATE TABLE tarefa
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    empresa_id     BIGINT,
    tipo_tarefa_id BIGINT,
    ingrediente_id BIGINT,
    relator_id     BIGINT,
    responsavel_id BIGINT,
    pedido_id      BIGINT,
    situacao       VARCHAR(255),
    data_criacao   date,
    data_tarefa    date,
    data_limite    date,
    data_conclusao date,
    CONSTRAINT pk_tarefa PRIMARY KEY (id)
);